SHELL             := /bin/sh
HOST              ?= 127.0.0.1
GITROOT           := $(shell git rev-parse --show-toplevel)
GIT_HASH          := $(shell git rev-parse --short HEAD)
BUILD_FOLDER      := $(GITROOT)/docker
GIT_BASE_URL      ?= gitlab.ct.mobagel.com
DEFAULT_BRANCH    ?= develop
COMPANY           := mobagel
TMP_DIR           ?= tmp
DOCKER_REGISTRY   := harbor.mobagel.com
DOCKER_CI         ?= $(DOCKER_REGISTRY)/core-tech-ci
DOCKER_RELEASE    ?= $(DOCKER_REGISTRY)/core-tech-release
USER_ID           := $(shell id -u)
GROUP_ID          := $(shell id -g)
CURRENT_UID       := $(USER_ID):$(GROUP_ID)
CI_JOB_ID         ?= local
ENVIRONMENT       ?= dev
ACTION            ?= dev
.DEFAULT_GOAL     := help
JINJA_VERSION     := 2.1.6
