name: publish package

on:
  push:
    branches:
      - 'develop'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install and Build
        env:
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
          AIRTABLE_I18N_BASE: ${{ secrets.AIRTABLE_I18N_BASE }}
          AIRTABLE_I18N_TABLE: ${{ secrets.AIRTABLE_I18N_TABLE }}
          AIRTABLE_I18N_VIEW: ${{ secrets.AIRTABLE_I18N_VIEW }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: |
          yarn
          echo "AIRTABLE_KEY=${AIRTABLE_KEY}" > .env
          echo "AIRTABLE_I18N_BASE=${AIRTABLE_I18N_BASE}" >> .env
          echo "AIRTABLE_I18N_TABLE=${AIRTABLE_I18N_TABLE}" >> .env
          echo "AIRTABLE_I18N_VIEW=${AIRTABLE_I18N_VIEW}" >> .env
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env
          echo "" >> .env
          yarn build
      - name: Deploy 🚀
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: dist
          absolute_build_dir: true
